### ISSUE TITLE
npm build does not use data from JSON files

### ISSUE THREAD

**Issue by Eldzej** [vituum/vite-plugin-liquid#2]
When using the following file structure (based on the provided example in [VItuum](https://github.com/vituum/vituum) repo)

![image](https://user-images.githubusercontent.com/22633986/230283826-424f03c0-9147-41c5-8351-a55acb391713.png)

and running `build`  npm script, the resulting HTML files are not build using any of the data present in the JSON files.

When running `dev` script, everything works fine

**Comment by lubomirblazekcz** [comment]
Fixed in 1.0
