### ISSUE TITLE
npm Build Cannot Find File

### ISSUE THREAD

**Issue by mishingo** [vituum/vite-plugin-liquid#4]
Currently I have .liquid files and using the layout tag for example:

`{% layout "pages/layouts/base.liquid" %}`

It works in development, but on build it fails with a message:

`[vite:build-html] ENOENT: Failed to lookup "pages/layouts/base.liquid" in "./src", line:2, col:3`

For it to work on build it required me to add the .html extension as such:

`{% layout "pages/layouts/base.liquid.html" %}`

But then this fails in development

**Comment by lubomirblazekcz** [comment]
You shouldn't add layouts directory to pages. Pages should be only for page route templates. Create the layouts directory outside, for example src/templates/layouts

**Comment by mishingo** [comment]
This resolves the issue thank you!
